### ISSUE TITLE
Automate release creation with changelog

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/github-workflows#135]
### Automatic Changelog Generation:

- Based on the specific configuration in `.github/release.yml` (`.github` repo).

    Example from https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes 

  ```yaml
  changelog:
    exclude:
      labels:
        - ignore-for-release
      authors:
        - octocat
    categories:
      - title: Breaking Changes 🛠
        labels:
          - Semver-Major
          - breaking-change
      - title: Exciting New Features 🎉
        labels:
          - Semver-Minor
          - enhancement
      - title: Other Changes
        labels:
          - "*"
  ```

- Excludes issues labeled with specific tags (e.g., ignore-for-release).

- Organizes changelogs into categories (e.g., "Breaking Changes 🛠", "Exciting New Features 🎉", "Other Changes").

### Update and Commit the CHANGELOG.md File:

- Automatically updates CHANGELOG.md with new release information.

- Commits the changes and pushes them to the repository.

### Create a GitHub Release:

- Creates a new GitHub release based on the pushed tag.

- Automatically includes the content from CHANGELOG.md in the release.
