### ISSUE TITLE
Automate the labelling of pull requests

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/github-workflows#137]
Automating the labelling of pull requests will help in achieving a cleaner changelog during releases. Here is the suggested configuration according to this workflow `https://github.com/actions/labeler`:

```yaml
documentation:
- changed-files:
  - any-glob-to-any-file: 
      - 'docs/*'
      - '**/*.md'

tests:
- changed-files:
  - any-glob-to-any-file: 'tests/*'

feature:
 - head-branch: ['^feature', 'feature', '^feat', 'feat']

bug:
 - head-branch: ['^bug', 'bug', '^fix', 'fix']

epic:
 - head-branch: ['^epic', 'epic']
```
